# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
- id: "pynudger"
  name: "pynudger"
  description: "Opinionated Python linter from opennudge"
  language: "python"
  entry: "pynudger"
  types:
    - "python"
...
