# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Cache Test"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/actions/pdm-*.yml"
      - ".github/workflows/cache-test.yml"
      - ".github/workflows/cache-reusable.yml"
      - ".github/workflows/cache-reusable-item.yml"
  merge_group:
    types:
      - "checks_requested"
  workflow_dispatch:

permissions: {} # yamllint disable-line rule:braces

jobs:
  cache-test:
    name: "Cache Test"
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/cache-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
...
