# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Docs"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.md"
      - "mkdocs.yml"
      - "docs/**"
      - "src/**.py"
      - ".github/actions/pdm-*.yml"
      - ".github/workflows/docs.yml"
      - ".github/workflows/docs-reusable.yml"
      - ".github/workflows/run-*reusable.yml"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

concurrency:
  cancel-in-progress: true
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}

jobs:
  docs:
    name: "Docs"
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/docs-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
...
