# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Generation Update Reusable"

on:
  workflow_call:
    inputs:
      pull-request:
        description: "Perform pull request if true"
        type: "boolean"
        default: false

permissions: {} # yamllint disable-line rule:braces

jobs:
  generation-update-reusable:
    timeout-minutes: 10
    name: "Generation Update Reusable"
    permissions:
      contents: "read"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0" # v2.12.0
        # yamllint enable rule:line-length
        with:
          disable-sudo-and-containers: true
          egress-policy: "block"
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pdm-project.org:443
            pdm.fming.dev:443
            pypi.org:443
            raw.githubusercontent.com:443
            endoflife.date:443
      - name: "Checkout repository" # zizmor: ignore[artipacked]
        # yamllint disable rule:line-length
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
        # yamllint enable rule:line-length
      - name: "Setup git credentials"
        # yamllint disable rule:line-length
        uses: "open-nudge/opentemplate/.github/actions/git-setup@main" # zizmor: ignore[unpinned-uses]
        # yamllint enable rule:line-length
      - name: "Setup PDM"
        # yamllint disable rule:line-length
        uses: "open-nudge/opentemplate/.github/actions/pdm-setup@main" # zizmor: ignore[unpinned-uses]
        # yamllint enable rule:line-length
        with:
          group: "generation"
      - name: "Create new branch"
        env:
          BRANCH_NAME: "bot/generation-update/${{ github.run_id }}"
        run: >
          git checkout -b "${BRANCH_NAME}"
      - name: "Update generation"
        run: >
          pdm run fix-generation
      - name: "Check changes"
        id: "check-changes"
        # yamllint disable rule:indentation
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        # yamllint enable rule:indentation
      - name: "Push changes"
        if: >
          steps.check-changes.outputs.changed == 'true' && inputs.pull-request
        # yamllint disable rule:line-length
        uses: "open-nudge/opentemplate/.github/actions/pull-request@main" # zizmor: ignore[unpinned-uses]
        # yamllint enable rule:line-length
        with:
          commit-message: "update static generation"
          branch-name: "bot/generation-update/${{ github.run_id }}"
...
