# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "GitHub Renovate"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/actions/*/action.yml"
      - ".github/workflows/*.yml"
      - ".github/renovate.json"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

jobs:
  github:
    name: "GitHub"
    if: |
      github.event.pull_request.user.login == 'renovate[bot]'
      && github.ref == 'refs/heads/bot/dependencies-dev-github'
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/github-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length

  github-actions:
    name: "GitHub Actions"
    if: |
      github.event.pull_request.user.login == 'renovate[bot]'
      && github.ref == 'refs/heads/bot/dependencies-dev-github'
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/github-actions-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length

  github-workflows:
    name: "GitHub Workflows"
    if: |
      github.event.pull_request.user.login == 'renovate[bot]'
      && github.ref == 'refs/heads/bot/dependencies-dev-github'
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/github-workflows-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length

  github-renovate:
    name: "GitHub Renovate"
    if: |
      github.event.pull_request.user.login == 'renovate[bot]'
      && github.ref == 'refs/heads/bot/dependencies-dev-github'
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/github-renovate-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
...
