# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Labeler"

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - "opened"
      - "edited"
      - "synchronize"
      - "reopened"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

jobs:
  labeler:
    timeout-minutes: 10
    name: "Labeler"
    permissions:
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0" # v2.12.0
        # yamllint enable rule:line-length
        with:
          disable-sudo-and-containers: true
          egress-policy: "block"
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
      - name: "Checkout repository"
        # yamllint disable rule:line-length
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
        # yamllint enable rule:line-length
        with:
          sparse-checkout: |
            .github
          sparse-checkout-cone-mode: true
          persist-credentials: false
      - name: "Label PR"
        # yamllint disable rule:line-length
        uses: "actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9" # v5.0.0
        # yamllint enable rule:line-length
        with:
          configuration-path: "./.github/label-path.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      - name: "PR Labeler"
        # yamllint disable rule:line-length
        uses: "github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685" # v3.4
        # yamllint enable rule:line-length
        with:
          configuration-path: ".github/label-title.yml"
          enable-versioned-regex: 0
          sync-labels: 1
          include-title: 1
          include-body: 0
...
