# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "pre-commit Reusable"

on:
  workflow_call:
    inputs:
      pull-request:
        description: "Perform pull request if true"
        type: "boolean"
        default: false

permissions: {} # yamllint disable-line rule:braces

jobs:
  pre-commit-reusable:
    timeout-minutes: 30
    name: "pre-commit Reusable"
    permissions:
      contents: "read"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0" # v2.12.0
        # yamllint enable rule:line-length
        with:
          disable-sudo-and-containers: true
          egress-policy: "block"
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            pdm-project.org:443
            pdm.fming.dev:443
            proxy.golang.org:443
            pypi.org:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443
            storage.googleapis.com:443
            sum.golang.org:443
            endoflife.date:443
            api.osv.dev:443
            api.deps.dev:443
            endoflife.date:443
            semgrep.dev:443
            fonts.google.com:443
            fonts.gstatic.com:443
            release-assets.githubusercontent.com:443
      - name: "Checkout repository" # zizmor: ignore[artipacked]
        # yamllint disable rule:line-length
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
        # yamllint enable rule:line-length
      - name: "Setup git credentials"
        # yamllint disable rule:line-length
        uses: "open-nudge/opentemplate/.github/actions/git-setup@main" # zizmor: ignore[unpinned-uses]
        # yamllint enable rule:line-length
      - name: "Setup PDM"
        # yamllint disable rule:line-length
        uses: "open-nudge/opentemplate/.github/actions/pdm-setup@main" # zizmor: ignore[unpinned-uses]
        # yamllint enable rule:line-length
        with:
          all: true
      - name: "Create new branch"
        env:
          BRANCH_NAME: "bot/pre-commit-update/${{ github.run_id }}"
        run: >
          git checkout -b "${BRANCH_NAME}"
      - name: "Update pre-commit dependencies"
        run: >
          pdm run -v pre-commit autoupdate --freeze
      - name: "Check for changes"
        id: "check-changes"
        # yamllint disable rule:indentation
        run: |
          if git diff --exit-code .pre-commit-config.yaml; then
            echo "changed=false" >> "${GITHUB_OUTPUT}"
          else
            echo "changed=true" >> "${GITHUB_OUTPUT}"
          fi
        # yamllint enable rule:indentation
      - name: "Run pre-commit with updated dependencies"
        env:
          SKIP: "dco,vale,fix-legal,markdown"
        if: >
          steps.check-changes.outputs.changed == 'true'
        run: >
          pdm run -v pre-commit run --all-files
      - name: "[OPTIONAL] Push changes"
        if: >
          steps.check-changes.outputs.changed == 'true' && inputs.pull-request
        # yamllint disable rule:line-length
        uses: "open-nudge/opentemplate/.github/actions/pull-request@main" # zizmor: ignore[unpinned-uses]
        # yamllint enable rule:line-length
        with:
          commit-message: "update pre-commit dependencies"
          branch-name: "bot/pre-commit-update/${{ github.run_id }}"
      - name: "[OPTIONAL] Error if this is a check"
        if: >
          (! inputs.pull-request)
          && steps.check-changes.outputs.changed == 'true'
        # yamllint disable rule:line-length
        run: >
          echo "Pre-commit dependencies have been updated, please create a pull request to merge these changes." && exit 1
        # yamllint enable rule:line-length
...
