# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Pull Request"

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - "opened"
      - "edited"
      - "synchronize"
      - "reopened"
    branches:
      - "main"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    timeout-minutes: 10
    name: "Pull Request"
    permissions:
      pull-requests: "read"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0" # v2.12.0
        # yamllint enable rule:line-length
        with:
          disable-sudo-and-containers: true
          egress-policy: "block"
          allowed-endpoints: |
            api.github.com:443
      - name: "Lint Pull Request"
        # yamllint disable rule:line-length
        uses: "amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017" # v5.5.3
        # yamllint enable rule:line-length
        with:
          types: |
            fix
            feat
          requireScope: false
          disallowScopes: |
            .+
          subjectPattern: "^(?![A-Z]).+$"
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
...
