# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Release SBOMs Reusable"

on:
  workflow_call:

permissions: {} # yamllint disable-line rule:braces

jobs:
  # Works regardless of repo type
  sbom-legal:
    name: "SBOM Legal"
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/release-sbom-run-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      type: "legal"
      files: >-
        $(pdm run reuse lint --json | jq -r '.files[].path')
      group: "release"
      full-checkout: true

  # Works regardless of repo type (not really xD)
  sbom-legal-attest:
    name: "SBOM Legal Attest"
    needs:
      - "sbom-legal"
    # SLSA Level 3+ needs outside workflow to run to perform the signing
    permissions:
      id-token: "write"
      attestations: "write"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/release-sbom-attest-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      artifact: "${{ needs.sbom-legal.outputs.artifact }}"

  # Works regardless of repo type
  sbom-python-create-matrix:
    name: "Create Matrix"
    runs-on: "ubuntu-latest"
    permissions: {} # yamllint disable-line rule:braces
    outputs:
      matrix: "${{ steps.matrix.outputs.matrix }}"
    timeout-minutes: 10
    steps:
      - name: "Harden runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0" # v2.12.0
        # yamllint enable rule:line-length
        with:
          disable-sudo-and-containers: true
          egress-policy: "block"
          allowed-endpoints: >+
      - name: "Create Matrix"
        id: "matrix"
        # yamllint disable rule:indentation
        #
        #           DO NOT EDIT UNTIL end marker
        #
        # [[[cog
        # import json
        #
        # import cog
        # import cogeol
        #
        # versions = json.dumps(
        #     [v["cycle"] for v in reversed(cogeol.scientific())]
        # )
        #
        # cog.outl(f"""        run: |
        #           echo "matrix=$(echo '{{
        #             "python-version": {versions},
        #             "os": ["ubuntu-latest", "macos-latest", "windows-latest"],
        #             "dependencies": [
        #               {{"name": "dev", "group": "", "all": true}},
        #               {{"name": "package", "group": "release", "all": false}}
        #             ]
        #           }}' | jq -r 'tojson')" >> "${{GITHUB_OUTPUT}}\""""
        # )
        # ]]]
        run: |
          echo "matrix=$(echo '{
            "python-version": ["3.11", "3.12", "3.13"],
            "os": ["ubuntu-latest", "macos-latest", "windows-latest"],
            "dependencies": [
              {"name": "dev", "group": "", "all": true},
              {"name": "package", "group": "release", "all": false}
            ]
          }' | jq -r 'tojson')" >> "${GITHUB_OUTPUT}"
        # [[[end]]] (sum: q1QeclzB43)
        # yamllint enable rule:indentation

  # Works regardless of repo type
  sbom-python:
    needs:
      - "sbom-python-create-matrix"
    name: >
      SBOM |
      python-${{ matrix.python-version }} |
      ${{ matrix.os }} |
      ${{ matrix.dependencies.name }}
    strategy:
      fail-fast: true
      matrix: "${{ fromJson(needs.sbom-python-create-matrix.outputs.matrix) }}"
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/release-sbom-run-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      type: "python"
      # yamllint disable rule:line-length
      files: >-
        $(find .venv/lib -type f -name 'RECORD' -path '.venv/lib/*.dist-info/RECORD')
      # yamllint enable rule:line-length
      group: "${{ matrix.dependencies.group }}"
      core: true
      all: "${{ matrix.dependencies.all }}"
      os: "${{ matrix.os }}"
      python-version: "${{ matrix.python-version }}"

  # Works regardless of repo type
  sbom-python-attest:
    name: >
      SBOM Attest |
      python-${{ matrix.python-version }} |
      ${{ matrix.os }} |
      ${{ matrix.dependencies.name }}
    permissions:
      id-token: "write"
      attestations: "write"
    needs:
      - "sbom-python-create-matrix"
      - "sbom-python"
    strategy:
      fail-fast: true
      matrix: "${{ fromJson(needs.sbom-python-create-matrix.outputs.matrix) }}"

    # SLSA Level 3+ needs outside workflow to run to perform the signing
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/release-sbom-attest-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      # Unfortunately could not easily reuse the artifact from the sbom
      # yamllint disable rule:indentation
      artifact: "sbom-python-${{ matrix.dependencies.all
                    && format(
                      'all-{0}-{1}-{2}',
                      matrix.python-version,
                      matrix.os,
                      github.sha
                    )
                    || format(
                      '{0}-{1}-{2}-{3}-{4}',
                      'core',
                      matrix.dependencies.group != ''
                        && matrix.dependencies.group || 'none',
                      matrix.python-version,
                      matrix.os,
                      github.sha
                    )
                  }}"
      # yamllint enable rule:indentation

  sbom-github:
    name: "SBOM Github"
    timeout-minutes: 10
    runs-on: "ubuntu-latest"
    outputs:
      artifact: "${{ steps.setup.outputs.artifact }}"
    permissions:
      contents: "read"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0" # v2.12.0
        # yamllint enable rule:line-length
        with:
          disable-sudo-and-containers: true
          egress-policy: "block"
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - name: "Repository checkout"
        # yamllint disable rule:line-length
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
        # yamllint enable rule:line-length
        with:
          sparse-checkout: |
            .github/actions/release-sbom-setup
            .github/workflows
          persist-credentials: false
      - name: "Perform action setup"
        id: "setup"
        # yamllint disable rule:line-length
        uses: "open-nudge/opentemplate/.github/actions/release-sbom-setup@main" # zizmor: ignore[unpinned-uses]
        # yamllint enable rule:line-length
        with:
          identifier: "sbom-github-${{ github.sha }}"
          files: >-
            $(find .github/workflows -type f -name '*.yml')
      - name: "Create GitHub SPDX SBOM"
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SBOM_FILE: "${{ steps.setup.outputs.sbom }}"
        run: >
          gh api "/repos/${GITHUB_REPOSITORY}/dependency-graph/sbom"
          | jq '.sbom'
          > "${SBOM_FILE}"
      - name: "Upload artifacts"
        # yamllint disable rule:line-length
        uses: "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02" # v4.6.2
        # yamllint enable rule:line-length
        with:
          name: "${{ steps.setup.outputs.artifact }}"
          path: "${{ steps.setup.outputs.sbom-directory }}"
          retention-days: 1
          overwrite: true
          if-no-files-found: "error"

  # Works regardless of repo type
  sbom-github-attest:
    name: "SBOM GitHub Attest"
    permissions:
      id-token: "write"
      attestations: "write"
    needs:
      - "sbom-github"
    # SLSA Level 3+ needs outside workflow to run to perform the signing
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/release-sbom-attest-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    # May fail on private repos without access to private sigstore instance
    with:
      artifact: "${{ needs.sbom-github.outputs.artifact }}"
...
