# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Security Secrets"

on:
  pull_request:
    branches:
      - "main"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

jobs:
  security-secrets:
    timeout-minutes: 10
    permissions:
      # Only need to read contents
      contents: "read"
    name: "Security Secrets"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner" # zizmor: ignore[known-vulnerable-actions]
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0" # v2.12.0
        # yamllint enable rule:line-length
        with:
          # Uses docker container,
          # disable-sudo-and-containers impossible
          disable-sudo: true
          egress-policy: "block"
          allowed-endpoints: >
            ghcr.io:443
            github.com:443
            pkg-containers.githubusercontent.com:443
      - name: "Checkout repository"
        # yamllint disable rule:line-length
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
        # yamllint enable rule:line-length
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "TruffleHog OSS"
        # yamllint disable rule:line-length
        uses: "trufflesecurity/trufflehog@90694bf9af66e7536abc5824e7a87246dbf933cb" # v3.88.35
        # yamllint enable rule:line-length
        with:
          extra_args: "--debug --only-verified"
...
