# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Stale"
on:
  schedule:
    - cron: "0 3 * * 6"
  workflow_call:
  workflow_dispatch:

permissions: {} # yamllint disable-line rule:braces

jobs:
  stale:
    timeout-minutes: 10
    name: "Stale"
    permissions:
      issues: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0" # v2.12.0
        # yamllint enable rule:line-length
        with:
          disable-sudo-and-containers: true
          egress-policy: "block"
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - name: "Mark stale PRs"
        # yamllint disable rule:line-length
        uses: "actions/stale@5bef64f19d7facfb25b37b414482c7164d639639" # v9.1.0
        # yamllint enable rule:line-length
        with:
          stale-pr-message: >
            This pull request did not receive any commits in the last 7 days.
            Marking pull request as stale (push additional commits or
            merge to unstale it).
          close-pr-message: >
            This PR was stale for the last 7 days.
            Closing the PR (one can reopen it at any time
            by committing and/or merging).
          days-before-pr-stale: 14
          days-before-pr-close: 28
          stale-pr-label: "stale"
          close-pr-label: "expired"
          remove-pr-stale-when-updated: true
          labels-to-remove-when-unstale: "stale"
...
